#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GUI
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="QLRP")]
	public partial class QLRPDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertDinhDangPhim(DinhDangPhim instance);
    partial void UpdateDinhDangPhim(DinhDangPhim instance);
    partial void DeleteDinhDangPhim(DinhDangPhim instance);
    partial void InsertKhachHang(KhachHang instance);
    partial void UpdateKhachHang(KhachHang instance);
    partial void DeleteKhachHang(KhachHang instance);
    partial void InsertLichChieu(LichChieu instance);
    partial void UpdateLichChieu(LichChieu instance);
    partial void DeleteLichChieu(LichChieu instance);
    partial void InsertVe(Ve instance);
    partial void UpdateVe(Ve instance);
    partial void DeleteVe(Ve instance);
    partial void InsertTheLoai(TheLoai instance);
    partial void UpdateTheLoai(TheLoai instance);
    partial void DeleteTheLoai(TheLoai instance);
    partial void InsertPhongChieu(PhongChieu instance);
    partial void UpdatePhongChieu(PhongChieu instance);
    partial void DeletePhongChieu(PhongChieu instance);
    partial void InsertPhim(Phim instance);
    partial void UpdatePhim(Phim instance);
    partial void DeletePhim(Phim instance);
    partial void InsertPhanLoaiPhim(PhanLoaiPhim instance);
    partial void UpdatePhanLoaiPhim(PhanLoaiPhim instance);
    partial void DeletePhanLoaiPhim(PhanLoaiPhim instance);
    partial void InsertNhanVien(NhanVien instance);
    partial void UpdateNhanVien(NhanVien instance);
    partial void DeleteNhanVien(NhanVien instance);
    partial void InsertLoaiManHinh(LoaiManHinh instance);
    partial void UpdateLoaiManHinh(LoaiManHinh instance);
    partial void DeleteLoaiManHinh(LoaiManHinh instance);
    #endregion
		
		public QLRPDataContext() : 
				base(global::GUI.Properties.Settings.Default.QLRPConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public QLRPDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public QLRPDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public QLRPDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public QLRPDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<DinhDangPhim> DinhDangPhims
		{
			get
			{
				return this.GetTable<DinhDangPhim>();
			}
		}
		
		public System.Data.Linq.Table<KhachHang> KhachHangs
		{
			get
			{
				return this.GetTable<KhachHang>();
			}
		}
		
		public System.Data.Linq.Table<LichChieu> LichChieus
		{
			get
			{
				return this.GetTable<LichChieu>();
			}
		}
		
		public System.Data.Linq.Table<Ve> Ves
		{
			get
			{
				return this.GetTable<Ve>();
			}
		}
		
		public System.Data.Linq.Table<TheLoai> TheLoais
		{
			get
			{
				return this.GetTable<TheLoai>();
			}
		}
		
		public System.Data.Linq.Table<TaiKhoan> TaiKhoans
		{
			get
			{
				return this.GetTable<TaiKhoan>();
			}
		}
		
		public System.Data.Linq.Table<PhongChieu> PhongChieus
		{
			get
			{
				return this.GetTable<PhongChieu>();
			}
		}
		
		public System.Data.Linq.Table<Phim> Phims
		{
			get
			{
				return this.GetTable<Phim>();
			}
		}
		
		public System.Data.Linq.Table<PhanLoaiPhim> PhanLoaiPhims
		{
			get
			{
				return this.GetTable<PhanLoaiPhim>();
			}
		}
		
		public System.Data.Linq.Table<NhanVien> NhanViens
		{
			get
			{
				return this.GetTable<NhanVien>();
			}
		}
		
		public System.Data.Linq.Table<LoaiManHinh> LoaiManHinhs
		{
			get
			{
				return this.GetTable<LoaiManHinh>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.DinhDangPhim")]
	public partial class DinhDangPhim : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _id;
		
		private string _idPhim;
		
		private string _idLoaiManHinh;
		
		private EntitySet<LichChieu> _LichChieus;
		
		private EntityRef<Phim> _Phim;
		
		private EntityRef<LoaiManHinh> _LoaiManHinh;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(string value);
    partial void OnidChanged();
    partial void OnidPhimChanging(string value);
    partial void OnidPhimChanged();
    partial void OnidLoaiManHinhChanging(string value);
    partial void OnidLoaiManHinhChanged();
    #endregion
		
		public DinhDangPhim()
		{
			this._LichChieus = new EntitySet<LichChieu>(new Action<LichChieu>(this.attach_LichChieus), new Action<LichChieu>(this.detach_LichChieus));
			this._Phim = default(EntityRef<Phim>);
			this._LoaiManHinh = default(EntityRef<LoaiManHinh>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", DbType="VarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idPhim", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string idPhim
		{
			get
			{
				return this._idPhim;
			}
			set
			{
				if ((this._idPhim != value))
				{
					if (this._Phim.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnidPhimChanging(value);
					this.SendPropertyChanging();
					this._idPhim = value;
					this.SendPropertyChanged("idPhim");
					this.OnidPhimChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idLoaiManHinh", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string idLoaiManHinh
		{
			get
			{
				return this._idLoaiManHinh;
			}
			set
			{
				if ((this._idLoaiManHinh != value))
				{
					if (this._LoaiManHinh.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnidLoaiManHinhChanging(value);
					this.SendPropertyChanging();
					this._idLoaiManHinh = value;
					this.SendPropertyChanged("idLoaiManHinh");
					this.OnidLoaiManHinhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="DinhDangPhim_LichChieu", Storage="_LichChieus", ThisKey="id", OtherKey="idDinhDang")]
		public EntitySet<LichChieu> LichChieus
		{
			get
			{
				return this._LichChieus;
			}
			set
			{
				this._LichChieus.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Phim_DinhDangPhim", Storage="_Phim", ThisKey="idPhim", OtherKey="id", IsForeignKey=true)]
		public Phim Phim
		{
			get
			{
				return this._Phim.Entity;
			}
			set
			{
				Phim previousValue = this._Phim.Entity;
				if (((previousValue != value) 
							|| (this._Phim.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Phim.Entity = null;
						previousValue.DinhDangPhims.Remove(this);
					}
					this._Phim.Entity = value;
					if ((value != null))
					{
						value.DinhDangPhims.Add(this);
						this._idPhim = value.id;
					}
					else
					{
						this._idPhim = default(string);
					}
					this.SendPropertyChanged("Phim");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="LoaiManHinh_DinhDangPhim", Storage="_LoaiManHinh", ThisKey="idLoaiManHinh", OtherKey="id", IsForeignKey=true)]
		public LoaiManHinh LoaiManHinh
		{
			get
			{
				return this._LoaiManHinh.Entity;
			}
			set
			{
				LoaiManHinh previousValue = this._LoaiManHinh.Entity;
				if (((previousValue != value) 
							|| (this._LoaiManHinh.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._LoaiManHinh.Entity = null;
						previousValue.DinhDangPhims.Remove(this);
					}
					this._LoaiManHinh.Entity = value;
					if ((value != null))
					{
						value.DinhDangPhims.Add(this);
						this._idLoaiManHinh = value.id;
					}
					else
					{
						this._idLoaiManHinh = default(string);
					}
					this.SendPropertyChanged("LoaiManHinh");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_LichChieus(LichChieu entity)
		{
			this.SendPropertyChanging();
			entity.DinhDangPhim = this;
		}
		
		private void detach_LichChieus(LichChieu entity)
		{
			this.SendPropertyChanging();
			entity.DinhDangPhim = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.KhachHang")]
	public partial class KhachHang : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _id;
		
		private string _HoTen;
		
		private System.DateTime _NgaySinh;
		
		private string _DiaChi;
		
		private string _SDT;
		
		private int _CMND;
		
		private EntitySet<Ve> _Ves;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(string value);
    partial void OnidChanged();
    partial void OnHoTenChanging(string value);
    partial void OnHoTenChanged();
    partial void OnNgaySinhChanging(System.DateTime value);
    partial void OnNgaySinhChanged();
    partial void OnDiaChiChanging(string value);
    partial void OnDiaChiChanged();
    partial void OnSDTChanging(string value);
    partial void OnSDTChanged();
    partial void OnCMNDChanging(int value);
    partial void OnCMNDChanged();
    #endregion
		
		public KhachHang()
		{
			this._Ves = new EntitySet<Ve>(new Action<Ve>(this.attach_Ves), new Action<Ve>(this.detach_Ves));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", DbType="VarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HoTen", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string HoTen
		{
			get
			{
				return this._HoTen;
			}
			set
			{
				if ((this._HoTen != value))
				{
					this.OnHoTenChanging(value);
					this.SendPropertyChanging();
					this._HoTen = value;
					this.SendPropertyChanged("HoTen");
					this.OnHoTenChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgaySinh", DbType="Date NOT NULL")]
		public System.DateTime NgaySinh
		{
			get
			{
				return this._NgaySinh;
			}
			set
			{
				if ((this._NgaySinh != value))
				{
					this.OnNgaySinhChanging(value);
					this.SendPropertyChanging();
					this._NgaySinh = value;
					this.SendPropertyChanged("NgaySinh");
					this.OnNgaySinhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DiaChi", DbType="NVarChar(100)")]
		public string DiaChi
		{
			get
			{
				return this._DiaChi;
			}
			set
			{
				if ((this._DiaChi != value))
				{
					this.OnDiaChiChanging(value);
					this.SendPropertyChanging();
					this._DiaChi = value;
					this.SendPropertyChanged("DiaChi");
					this.OnDiaChiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SDT", DbType="VarChar(100)")]
		public string SDT
		{
			get
			{
				return this._SDT;
			}
			set
			{
				if ((this._SDT != value))
				{
					this.OnSDTChanging(value);
					this.SendPropertyChanging();
					this._SDT = value;
					this.SendPropertyChanged("SDT");
					this.OnSDTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CMND", DbType="Int NOT NULL")]
		public int CMND
		{
			get
			{
				return this._CMND;
			}
			set
			{
				if ((this._CMND != value))
				{
					this.OnCMNDChanging(value);
					this.SendPropertyChanging();
					this._CMND = value;
					this.SendPropertyChanged("CMND");
					this.OnCMNDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="KhachHang_Ve", Storage="_Ves", ThisKey="id", OtherKey="idKhachHang")]
		public EntitySet<Ve> Ves
		{
			get
			{
				return this._Ves;
			}
			set
			{
				this._Ves.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Ves(Ve entity)
		{
			this.SendPropertyChanging();
			entity.KhachHang = this;
		}
		
		private void detach_Ves(Ve entity)
		{
			this.SendPropertyChanging();
			entity.KhachHang = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.LichChieu")]
	public partial class LichChieu : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _id;
		
		private System.DateTime _ThoiGianChieu;
		
		private string _idPhong;
		
		private string _idDinhDang;
		
		private decimal _GiaVe;
		
		private int _TrangThai;
		
		private EntitySet<Ve> _Ves;
		
		private EntityRef<DinhDangPhim> _DinhDangPhim;
		
		private EntityRef<PhongChieu> _PhongChieu;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(string value);
    partial void OnidChanged();
    partial void OnThoiGianChieuChanging(System.DateTime value);
    partial void OnThoiGianChieuChanged();
    partial void OnidPhongChanging(string value);
    partial void OnidPhongChanged();
    partial void OnidDinhDangChanging(string value);
    partial void OnidDinhDangChanged();
    partial void OnGiaVeChanging(decimal value);
    partial void OnGiaVeChanged();
    partial void OnTrangThaiChanging(int value);
    partial void OnTrangThaiChanged();
    #endregion
		
		public LichChieu()
		{
			this._Ves = new EntitySet<Ve>(new Action<Ve>(this.attach_Ves), new Action<Ve>(this.detach_Ves));
			this._DinhDangPhim = default(EntityRef<DinhDangPhim>);
			this._PhongChieu = default(EntityRef<PhongChieu>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", DbType="VarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ThoiGianChieu", DbType="DateTime NOT NULL")]
		public System.DateTime ThoiGianChieu
		{
			get
			{
				return this._ThoiGianChieu;
			}
			set
			{
				if ((this._ThoiGianChieu != value))
				{
					this.OnThoiGianChieuChanging(value);
					this.SendPropertyChanging();
					this._ThoiGianChieu = value;
					this.SendPropertyChanged("ThoiGianChieu");
					this.OnThoiGianChieuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idPhong", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string idPhong
		{
			get
			{
				return this._idPhong;
			}
			set
			{
				if ((this._idPhong != value))
				{
					if (this._PhongChieu.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnidPhongChanging(value);
					this.SendPropertyChanging();
					this._idPhong = value;
					this.SendPropertyChanged("idPhong");
					this.OnidPhongChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idDinhDang", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string idDinhDang
		{
			get
			{
				return this._idDinhDang;
			}
			set
			{
				if ((this._idDinhDang != value))
				{
					if (this._DinhDangPhim.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnidDinhDangChanging(value);
					this.SendPropertyChanging();
					this._idDinhDang = value;
					this.SendPropertyChanged("idDinhDang");
					this.OnidDinhDangChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GiaVe", DbType="Money NOT NULL")]
		public decimal GiaVe
		{
			get
			{
				return this._GiaVe;
			}
			set
			{
				if ((this._GiaVe != value))
				{
					this.OnGiaVeChanging(value);
					this.SendPropertyChanging();
					this._GiaVe = value;
					this.SendPropertyChanged("GiaVe");
					this.OnGiaVeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TrangThai", DbType="Int NOT NULL")]
		public int TrangThai
		{
			get
			{
				return this._TrangThai;
			}
			set
			{
				if ((this._TrangThai != value))
				{
					this.OnTrangThaiChanging(value);
					this.SendPropertyChanging();
					this._TrangThai = value;
					this.SendPropertyChanged("TrangThai");
					this.OnTrangThaiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="LichChieu_Ve", Storage="_Ves", ThisKey="id", OtherKey="idLichChieu")]
		public EntitySet<Ve> Ves
		{
			get
			{
				return this._Ves;
			}
			set
			{
				this._Ves.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="DinhDangPhim_LichChieu", Storage="_DinhDangPhim", ThisKey="idDinhDang", OtherKey="id", IsForeignKey=true)]
		public DinhDangPhim DinhDangPhim
		{
			get
			{
				return this._DinhDangPhim.Entity;
			}
			set
			{
				DinhDangPhim previousValue = this._DinhDangPhim.Entity;
				if (((previousValue != value) 
							|| (this._DinhDangPhim.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._DinhDangPhim.Entity = null;
						previousValue.LichChieus.Remove(this);
					}
					this._DinhDangPhim.Entity = value;
					if ((value != null))
					{
						value.LichChieus.Add(this);
						this._idDinhDang = value.id;
					}
					else
					{
						this._idDinhDang = default(string);
					}
					this.SendPropertyChanged("DinhDangPhim");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="PhongChieu_LichChieu", Storage="_PhongChieu", ThisKey="idPhong", OtherKey="id", IsForeignKey=true)]
		public PhongChieu PhongChieu
		{
			get
			{
				return this._PhongChieu.Entity;
			}
			set
			{
				PhongChieu previousValue = this._PhongChieu.Entity;
				if (((previousValue != value) 
							|| (this._PhongChieu.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._PhongChieu.Entity = null;
						previousValue.LichChieus.Remove(this);
					}
					this._PhongChieu.Entity = value;
					if ((value != null))
					{
						value.LichChieus.Add(this);
						this._idPhong = value.id;
					}
					else
					{
						this._idPhong = default(string);
					}
					this.SendPropertyChanged("PhongChieu");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Ves(Ve entity)
		{
			this.SendPropertyChanging();
			entity.LichChieu = this;
		}
		
		private void detach_Ves(Ve entity)
		{
			this.SendPropertyChanging();
			entity.LichChieu = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Ve")]
	public partial class Ve : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private System.Nullable<int> _LoaiVe;
		
		private string _idLichChieu;
		
		private string _MaGheNgoi;
		
		private string _idKhachHang;
		
		private int _TrangThai;
		
		private System.Nullable<decimal> _TienBanVe;
		
		private EntityRef<KhachHang> _KhachHang;
		
		private EntityRef<LichChieu> _LichChieu;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OnLoaiVeChanging(System.Nullable<int> value);
    partial void OnLoaiVeChanged();
    partial void OnidLichChieuChanging(string value);
    partial void OnidLichChieuChanged();
    partial void OnMaGheNgoiChanging(string value);
    partial void OnMaGheNgoiChanged();
    partial void OnidKhachHangChanging(string value);
    partial void OnidKhachHangChanged();
    partial void OnTrangThaiChanging(int value);
    partial void OnTrangThaiChanged();
    partial void OnTienBanVeChanging(System.Nullable<decimal> value);
    partial void OnTienBanVeChanged();
    #endregion
		
		public Ve()
		{
			this._KhachHang = default(EntityRef<KhachHang>);
			this._LichChieu = default(EntityRef<LichChieu>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LoaiVe", DbType="Int")]
		public System.Nullable<int> LoaiVe
		{
			get
			{
				return this._LoaiVe;
			}
			set
			{
				if ((this._LoaiVe != value))
				{
					this.OnLoaiVeChanging(value);
					this.SendPropertyChanging();
					this._LoaiVe = value;
					this.SendPropertyChanged("LoaiVe");
					this.OnLoaiVeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idLichChieu", DbType="VarChar(50)")]
		public string idLichChieu
		{
			get
			{
				return this._idLichChieu;
			}
			set
			{
				if ((this._idLichChieu != value))
				{
					if (this._LichChieu.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnidLichChieuChanging(value);
					this.SendPropertyChanging();
					this._idLichChieu = value;
					this.SendPropertyChanged("idLichChieu");
					this.OnidLichChieuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaGheNgoi", DbType="VarChar(50)")]
		public string MaGheNgoi
		{
			get
			{
				return this._MaGheNgoi;
			}
			set
			{
				if ((this._MaGheNgoi != value))
				{
					this.OnMaGheNgoiChanging(value);
					this.SendPropertyChanging();
					this._MaGheNgoi = value;
					this.SendPropertyChanged("MaGheNgoi");
					this.OnMaGheNgoiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idKhachHang", DbType="VarChar(50)")]
		public string idKhachHang
		{
			get
			{
				return this._idKhachHang;
			}
			set
			{
				if ((this._idKhachHang != value))
				{
					if (this._KhachHang.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnidKhachHangChanging(value);
					this.SendPropertyChanging();
					this._idKhachHang = value;
					this.SendPropertyChanged("idKhachHang");
					this.OnidKhachHangChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TrangThai", DbType="Int NOT NULL")]
		public int TrangThai
		{
			get
			{
				return this._TrangThai;
			}
			set
			{
				if ((this._TrangThai != value))
				{
					this.OnTrangThaiChanging(value);
					this.SendPropertyChanging();
					this._TrangThai = value;
					this.SendPropertyChanged("TrangThai");
					this.OnTrangThaiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TienBanVe", DbType="Money")]
		public System.Nullable<decimal> TienBanVe
		{
			get
			{
				return this._TienBanVe;
			}
			set
			{
				if ((this._TienBanVe != value))
				{
					this.OnTienBanVeChanging(value);
					this.SendPropertyChanging();
					this._TienBanVe = value;
					this.SendPropertyChanged("TienBanVe");
					this.OnTienBanVeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="KhachHang_Ve", Storage="_KhachHang", ThisKey="idKhachHang", OtherKey="id", IsForeignKey=true)]
		public KhachHang KhachHang
		{
			get
			{
				return this._KhachHang.Entity;
			}
			set
			{
				KhachHang previousValue = this._KhachHang.Entity;
				if (((previousValue != value) 
							|| (this._KhachHang.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._KhachHang.Entity = null;
						previousValue.Ves.Remove(this);
					}
					this._KhachHang.Entity = value;
					if ((value != null))
					{
						value.Ves.Add(this);
						this._idKhachHang = value.id;
					}
					else
					{
						this._idKhachHang = default(string);
					}
					this.SendPropertyChanged("KhachHang");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="LichChieu_Ve", Storage="_LichChieu", ThisKey="idLichChieu", OtherKey="id", IsForeignKey=true)]
		public LichChieu LichChieu
		{
			get
			{
				return this._LichChieu.Entity;
			}
			set
			{
				LichChieu previousValue = this._LichChieu.Entity;
				if (((previousValue != value) 
							|| (this._LichChieu.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._LichChieu.Entity = null;
						previousValue.Ves.Remove(this);
					}
					this._LichChieu.Entity = value;
					if ((value != null))
					{
						value.Ves.Add(this);
						this._idLichChieu = value.id;
					}
					else
					{
						this._idLichChieu = default(string);
					}
					this.SendPropertyChanged("LichChieu");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TheLoai")]
	public partial class TheLoai : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _id;
		
		private string _TenTheLoai;
		
		private string _MoTa;
		
		private EntitySet<PhanLoaiPhim> _PhanLoaiPhims;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(string value);
    partial void OnidChanged();
    partial void OnTenTheLoaiChanging(string value);
    partial void OnTenTheLoaiChanged();
    partial void OnMoTaChanging(string value);
    partial void OnMoTaChanged();
    #endregion
		
		public TheLoai()
		{
			this._PhanLoaiPhims = new EntitySet<PhanLoaiPhim>(new Action<PhanLoaiPhim>(this.attach_PhanLoaiPhims), new Action<PhanLoaiPhim>(this.detach_PhanLoaiPhims));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", DbType="VarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenTheLoai", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string TenTheLoai
		{
			get
			{
				return this._TenTheLoai;
			}
			set
			{
				if ((this._TenTheLoai != value))
				{
					this.OnTenTheLoaiChanging(value);
					this.SendPropertyChanging();
					this._TenTheLoai = value;
					this.SendPropertyChanged("TenTheLoai");
					this.OnTenTheLoaiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MoTa", DbType="NVarChar(100)")]
		public string MoTa
		{
			get
			{
				return this._MoTa;
			}
			set
			{
				if ((this._MoTa != value))
				{
					this.OnMoTaChanging(value);
					this.SendPropertyChanging();
					this._MoTa = value;
					this.SendPropertyChanged("MoTa");
					this.OnMoTaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TheLoai_PhanLoaiPhim", Storage="_PhanLoaiPhims", ThisKey="id", OtherKey="idTheLoai")]
		public EntitySet<PhanLoaiPhim> PhanLoaiPhims
		{
			get
			{
				return this._PhanLoaiPhims;
			}
			set
			{
				this._PhanLoaiPhims.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_PhanLoaiPhims(PhanLoaiPhim entity)
		{
			this.SendPropertyChanging();
			entity.TheLoai = this;
		}
		
		private void detach_PhanLoaiPhims(PhanLoaiPhim entity)
		{
			this.SendPropertyChanging();
			entity.TheLoai = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TaiKhoan")]
	public partial class TaiKhoan
	{
		
		private string _UserName;
		
		private string _Pass;
		
		private int _LoaiTK;
		
		private string _idNV;
		
		public TaiKhoan()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UserName", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string UserName
		{
			get
			{
				return this._UserName;
			}
			set
			{
				if ((this._UserName != value))
				{
					this._UserName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Pass", DbType="VarChar(1000) NOT NULL", CanBeNull=false)]
		public string Pass
		{
			get
			{
				return this._Pass;
			}
			set
			{
				if ((this._Pass != value))
				{
					this._Pass = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LoaiTK", DbType="Int NOT NULL")]
		public int LoaiTK
		{
			get
			{
				return this._LoaiTK;
			}
			set
			{
				if ((this._LoaiTK != value))
				{
					this._LoaiTK = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idNV", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string idNV
		{
			get
			{
				return this._idNV;
			}
			set
			{
				if ((this._idNV != value))
				{
					this._idNV = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.PhongChieu")]
	public partial class PhongChieu : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _id;
		
		private string _TenPhong;
		
		private string _idManHinh;
		
		private int _SoChoNgoi;
		
		private int _TinhTrang;
		
		private int _SoHangGhe;
		
		private int _SoGheMotHang;
		
		private EntitySet<LichChieu> _LichChieus;
		
		private EntityRef<LoaiManHinh> _LoaiManHinh;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(string value);
    partial void OnidChanged();
    partial void OnTenPhongChanging(string value);
    partial void OnTenPhongChanged();
    partial void OnidManHinhChanging(string value);
    partial void OnidManHinhChanged();
    partial void OnSoChoNgoiChanging(int value);
    partial void OnSoChoNgoiChanged();
    partial void OnTinhTrangChanging(int value);
    partial void OnTinhTrangChanged();
    partial void OnSoHangGheChanging(int value);
    partial void OnSoHangGheChanged();
    partial void OnSoGheMotHangChanging(int value);
    partial void OnSoGheMotHangChanged();
    #endregion
		
		public PhongChieu()
		{
			this._LichChieus = new EntitySet<LichChieu>(new Action<LichChieu>(this.attach_LichChieus), new Action<LichChieu>(this.detach_LichChieus));
			this._LoaiManHinh = default(EntityRef<LoaiManHinh>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", DbType="VarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenPhong", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string TenPhong
		{
			get
			{
				return this._TenPhong;
			}
			set
			{
				if ((this._TenPhong != value))
				{
					this.OnTenPhongChanging(value);
					this.SendPropertyChanging();
					this._TenPhong = value;
					this.SendPropertyChanged("TenPhong");
					this.OnTenPhongChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idManHinh", DbType="VarChar(50)")]
		public string idManHinh
		{
			get
			{
				return this._idManHinh;
			}
			set
			{
				if ((this._idManHinh != value))
				{
					if (this._LoaiManHinh.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnidManHinhChanging(value);
					this.SendPropertyChanging();
					this._idManHinh = value;
					this.SendPropertyChanged("idManHinh");
					this.OnidManHinhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SoChoNgoi", DbType="Int NOT NULL")]
		public int SoChoNgoi
		{
			get
			{
				return this._SoChoNgoi;
			}
			set
			{
				if ((this._SoChoNgoi != value))
				{
					this.OnSoChoNgoiChanging(value);
					this.SendPropertyChanging();
					this._SoChoNgoi = value;
					this.SendPropertyChanged("SoChoNgoi");
					this.OnSoChoNgoiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TinhTrang", DbType="Int NOT NULL")]
		public int TinhTrang
		{
			get
			{
				return this._TinhTrang;
			}
			set
			{
				if ((this._TinhTrang != value))
				{
					this.OnTinhTrangChanging(value);
					this.SendPropertyChanging();
					this._TinhTrang = value;
					this.SendPropertyChanged("TinhTrang");
					this.OnTinhTrangChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SoHangGhe", DbType="Int NOT NULL")]
		public int SoHangGhe
		{
			get
			{
				return this._SoHangGhe;
			}
			set
			{
				if ((this._SoHangGhe != value))
				{
					this.OnSoHangGheChanging(value);
					this.SendPropertyChanging();
					this._SoHangGhe = value;
					this.SendPropertyChanged("SoHangGhe");
					this.OnSoHangGheChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SoGheMotHang", DbType="Int NOT NULL")]
		public int SoGheMotHang
		{
			get
			{
				return this._SoGheMotHang;
			}
			set
			{
				if ((this._SoGheMotHang != value))
				{
					this.OnSoGheMotHangChanging(value);
					this.SendPropertyChanging();
					this._SoGheMotHang = value;
					this.SendPropertyChanged("SoGheMotHang");
					this.OnSoGheMotHangChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="PhongChieu_LichChieu", Storage="_LichChieus", ThisKey="id", OtherKey="idPhong")]
		public EntitySet<LichChieu> LichChieus
		{
			get
			{
				return this._LichChieus;
			}
			set
			{
				this._LichChieus.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="LoaiManHinh_PhongChieu", Storage="_LoaiManHinh", ThisKey="idManHinh", OtherKey="id", IsForeignKey=true)]
		public LoaiManHinh LoaiManHinh
		{
			get
			{
				return this._LoaiManHinh.Entity;
			}
			set
			{
				LoaiManHinh previousValue = this._LoaiManHinh.Entity;
				if (((previousValue != value) 
							|| (this._LoaiManHinh.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._LoaiManHinh.Entity = null;
						previousValue.PhongChieus.Remove(this);
					}
					this._LoaiManHinh.Entity = value;
					if ((value != null))
					{
						value.PhongChieus.Add(this);
						this._idManHinh = value.id;
					}
					else
					{
						this._idManHinh = default(string);
					}
					this.SendPropertyChanged("LoaiManHinh");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_LichChieus(LichChieu entity)
		{
			this.SendPropertyChanging();
			entity.PhongChieu = this;
		}
		
		private void detach_LichChieus(LichChieu entity)
		{
			this.SendPropertyChanging();
			entity.PhongChieu = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Phim")]
	public partial class Phim : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _id;
		
		private string _TenPhim;
		
		private string _MoTa;
		
		private double _ThoiLuong;
		
		private System.DateTime _NgayKhoiChieu;
		
		private System.DateTime _NgayKetThuc;
		
		private string _SanXuat;
		
		private string _DaoDien;
		
		private int _NamSX;
		
		private System.Data.Linq.Binary _ApPhich;
		
		private EntitySet<DinhDangPhim> _DinhDangPhims;
		
		private EntitySet<PhanLoaiPhim> _PhanLoaiPhims;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(string value);
    partial void OnidChanged();
    partial void OnTenPhimChanging(string value);
    partial void OnTenPhimChanged();
    partial void OnMoTaChanging(string value);
    partial void OnMoTaChanged();
    partial void OnThoiLuongChanging(double value);
    partial void OnThoiLuongChanged();
    partial void OnNgayKhoiChieuChanging(System.DateTime value);
    partial void OnNgayKhoiChieuChanged();
    partial void OnNgayKetThucChanging(System.DateTime value);
    partial void OnNgayKetThucChanged();
    partial void OnSanXuatChanging(string value);
    partial void OnSanXuatChanged();
    partial void OnDaoDienChanging(string value);
    partial void OnDaoDienChanged();
    partial void OnNamSXChanging(int value);
    partial void OnNamSXChanged();
    partial void OnApPhichChanging(System.Data.Linq.Binary value);
    partial void OnApPhichChanged();
    #endregion
		
		public Phim()
		{
			this._DinhDangPhims = new EntitySet<DinhDangPhim>(new Action<DinhDangPhim>(this.attach_DinhDangPhims), new Action<DinhDangPhim>(this.detach_DinhDangPhims));
			this._PhanLoaiPhims = new EntitySet<PhanLoaiPhim>(new Action<PhanLoaiPhim>(this.attach_PhanLoaiPhims), new Action<PhanLoaiPhim>(this.detach_PhanLoaiPhims));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", DbType="VarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenPhim", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string TenPhim
		{
			get
			{
				return this._TenPhim;
			}
			set
			{
				if ((this._TenPhim != value))
				{
					this.OnTenPhimChanging(value);
					this.SendPropertyChanging();
					this._TenPhim = value;
					this.SendPropertyChanged("TenPhim");
					this.OnTenPhimChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MoTa", DbType="NVarChar(1000)")]
		public string MoTa
		{
			get
			{
				return this._MoTa;
			}
			set
			{
				if ((this._MoTa != value))
				{
					this.OnMoTaChanging(value);
					this.SendPropertyChanging();
					this._MoTa = value;
					this.SendPropertyChanged("MoTa");
					this.OnMoTaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ThoiLuong", DbType="Float NOT NULL")]
		public double ThoiLuong
		{
			get
			{
				return this._ThoiLuong;
			}
			set
			{
				if ((this._ThoiLuong != value))
				{
					this.OnThoiLuongChanging(value);
					this.SendPropertyChanging();
					this._ThoiLuong = value;
					this.SendPropertyChanged("ThoiLuong");
					this.OnThoiLuongChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgayKhoiChieu", DbType="Date NOT NULL")]
		public System.DateTime NgayKhoiChieu
		{
			get
			{
				return this._NgayKhoiChieu;
			}
			set
			{
				if ((this._NgayKhoiChieu != value))
				{
					this.OnNgayKhoiChieuChanging(value);
					this.SendPropertyChanging();
					this._NgayKhoiChieu = value;
					this.SendPropertyChanged("NgayKhoiChieu");
					this.OnNgayKhoiChieuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgayKetThuc", DbType="Date NOT NULL")]
		public System.DateTime NgayKetThuc
		{
			get
			{
				return this._NgayKetThuc;
			}
			set
			{
				if ((this._NgayKetThuc != value))
				{
					this.OnNgayKetThucChanging(value);
					this.SendPropertyChanging();
					this._NgayKetThuc = value;
					this.SendPropertyChanged("NgayKetThuc");
					this.OnNgayKetThucChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SanXuat", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string SanXuat
		{
			get
			{
				return this._SanXuat;
			}
			set
			{
				if ((this._SanXuat != value))
				{
					this.OnSanXuatChanging(value);
					this.SendPropertyChanging();
					this._SanXuat = value;
					this.SendPropertyChanged("SanXuat");
					this.OnSanXuatChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DaoDien", DbType="NVarChar(100)")]
		public string DaoDien
		{
			get
			{
				return this._DaoDien;
			}
			set
			{
				if ((this._DaoDien != value))
				{
					this.OnDaoDienChanging(value);
					this.SendPropertyChanging();
					this._DaoDien = value;
					this.SendPropertyChanged("DaoDien");
					this.OnDaoDienChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NamSX", DbType="Int NOT NULL")]
		public int NamSX
		{
			get
			{
				return this._NamSX;
			}
			set
			{
				if ((this._NamSX != value))
				{
					this.OnNamSXChanging(value);
					this.SendPropertyChanging();
					this._NamSX = value;
					this.SendPropertyChanged("NamSX");
					this.OnNamSXChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ApPhich", DbType="Image", UpdateCheck=UpdateCheck.Never)]
		public System.Data.Linq.Binary ApPhich
		{
			get
			{
				return this._ApPhich;
			}
			set
			{
				if ((this._ApPhich != value))
				{
					this.OnApPhichChanging(value);
					this.SendPropertyChanging();
					this._ApPhich = value;
					this.SendPropertyChanged("ApPhich");
					this.OnApPhichChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Phim_DinhDangPhim", Storage="_DinhDangPhims", ThisKey="id", OtherKey="idPhim")]
		public EntitySet<DinhDangPhim> DinhDangPhims
		{
			get
			{
				return this._DinhDangPhims;
			}
			set
			{
				this._DinhDangPhims.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Phim_PhanLoaiPhim", Storage="_PhanLoaiPhims", ThisKey="id", OtherKey="idPhim")]
		public EntitySet<PhanLoaiPhim> PhanLoaiPhims
		{
			get
			{
				return this._PhanLoaiPhims;
			}
			set
			{
				this._PhanLoaiPhims.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_DinhDangPhims(DinhDangPhim entity)
		{
			this.SendPropertyChanging();
			entity.Phim = this;
		}
		
		private void detach_DinhDangPhims(DinhDangPhim entity)
		{
			this.SendPropertyChanging();
			entity.Phim = null;
		}
		
		private void attach_PhanLoaiPhims(PhanLoaiPhim entity)
		{
			this.SendPropertyChanging();
			entity.Phim = this;
		}
		
		private void detach_PhanLoaiPhims(PhanLoaiPhim entity)
		{
			this.SendPropertyChanging();
			entity.Phim = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.PhanLoaiPhim")]
	public partial class PhanLoaiPhim : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _idPhim;
		
		private string _idTheLoai;
		
		private EntityRef<Phim> _Phim;
		
		private EntityRef<TheLoai> _TheLoai;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidPhimChanging(string value);
    partial void OnidPhimChanged();
    partial void OnidTheLoaiChanging(string value);
    partial void OnidTheLoaiChanged();
    #endregion
		
		public PhanLoaiPhim()
		{
			this._Phim = default(EntityRef<Phim>);
			this._TheLoai = default(EntityRef<TheLoai>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idPhim", DbType="VarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string idPhim
		{
			get
			{
				return this._idPhim;
			}
			set
			{
				if ((this._idPhim != value))
				{
					if (this._Phim.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnidPhimChanging(value);
					this.SendPropertyChanging();
					this._idPhim = value;
					this.SendPropertyChanged("idPhim");
					this.OnidPhimChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idTheLoai", DbType="VarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string idTheLoai
		{
			get
			{
				return this._idTheLoai;
			}
			set
			{
				if ((this._idTheLoai != value))
				{
					if (this._TheLoai.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnidTheLoaiChanging(value);
					this.SendPropertyChanging();
					this._idTheLoai = value;
					this.SendPropertyChanged("idTheLoai");
					this.OnidTheLoaiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Phim_PhanLoaiPhim", Storage="_Phim", ThisKey="idPhim", OtherKey="id", IsForeignKey=true)]
		public Phim Phim
		{
			get
			{
				return this._Phim.Entity;
			}
			set
			{
				Phim previousValue = this._Phim.Entity;
				if (((previousValue != value) 
							|| (this._Phim.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Phim.Entity = null;
						previousValue.PhanLoaiPhims.Remove(this);
					}
					this._Phim.Entity = value;
					if ((value != null))
					{
						value.PhanLoaiPhims.Add(this);
						this._idPhim = value.id;
					}
					else
					{
						this._idPhim = default(string);
					}
					this.SendPropertyChanged("Phim");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TheLoai_PhanLoaiPhim", Storage="_TheLoai", ThisKey="idTheLoai", OtherKey="id", IsForeignKey=true)]
		public TheLoai TheLoai
		{
			get
			{
				return this._TheLoai.Entity;
			}
			set
			{
				TheLoai previousValue = this._TheLoai.Entity;
				if (((previousValue != value) 
							|| (this._TheLoai.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._TheLoai.Entity = null;
						previousValue.PhanLoaiPhims.Remove(this);
					}
					this._TheLoai.Entity = value;
					if ((value != null))
					{
						value.PhanLoaiPhims.Add(this);
						this._idTheLoai = value.id;
					}
					else
					{
						this._idTheLoai = default(string);
					}
					this.SendPropertyChanged("TheLoai");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.NhanVien")]
	public partial class NhanVien : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _id;
		
		private string _HoTen;
		
		private System.DateTime _NgaySinh;
		
		private string _DiaChi;
		
		private string _SDT;
		
		private int _CMND;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(string value);
    partial void OnidChanged();
    partial void OnHoTenChanging(string value);
    partial void OnHoTenChanged();
    partial void OnNgaySinhChanging(System.DateTime value);
    partial void OnNgaySinhChanged();
    partial void OnDiaChiChanging(string value);
    partial void OnDiaChiChanged();
    partial void OnSDTChanging(string value);
    partial void OnSDTChanged();
    partial void OnCMNDChanging(int value);
    partial void OnCMNDChanged();
    #endregion
		
		public NhanVien()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", DbType="VarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HoTen", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string HoTen
		{
			get
			{
				return this._HoTen;
			}
			set
			{
				if ((this._HoTen != value))
				{
					this.OnHoTenChanging(value);
					this.SendPropertyChanging();
					this._HoTen = value;
					this.SendPropertyChanged("HoTen");
					this.OnHoTenChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgaySinh", DbType="Date NOT NULL")]
		public System.DateTime NgaySinh
		{
			get
			{
				return this._NgaySinh;
			}
			set
			{
				if ((this._NgaySinh != value))
				{
					this.OnNgaySinhChanging(value);
					this.SendPropertyChanging();
					this._NgaySinh = value;
					this.SendPropertyChanged("NgaySinh");
					this.OnNgaySinhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DiaChi", DbType="NVarChar(100)")]
		public string DiaChi
		{
			get
			{
				return this._DiaChi;
			}
			set
			{
				if ((this._DiaChi != value))
				{
					this.OnDiaChiChanging(value);
					this.SendPropertyChanging();
					this._DiaChi = value;
					this.SendPropertyChanged("DiaChi");
					this.OnDiaChiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SDT", DbType="VarChar(100)")]
		public string SDT
		{
			get
			{
				return this._SDT;
			}
			set
			{
				if ((this._SDT != value))
				{
					this.OnSDTChanging(value);
					this.SendPropertyChanging();
					this._SDT = value;
					this.SendPropertyChanged("SDT");
					this.OnSDTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CMND", DbType="Int NOT NULL")]
		public int CMND
		{
			get
			{
				return this._CMND;
			}
			set
			{
				if ((this._CMND != value))
				{
					this.OnCMNDChanging(value);
					this.SendPropertyChanging();
					this._CMND = value;
					this.SendPropertyChanged("CMND");
					this.OnCMNDChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.LoaiManHinh")]
	public partial class LoaiManHinh : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _id;
		
		private string _TenMH;
		
		private EntitySet<DinhDangPhim> _DinhDangPhims;
		
		private EntitySet<PhongChieu> _PhongChieus;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(string value);
    partial void OnidChanged();
    partial void OnTenMHChanging(string value);
    partial void OnTenMHChanged();
    #endregion
		
		public LoaiManHinh()
		{
			this._DinhDangPhims = new EntitySet<DinhDangPhim>(new Action<DinhDangPhim>(this.attach_DinhDangPhims), new Action<DinhDangPhim>(this.detach_DinhDangPhims));
			this._PhongChieus = new EntitySet<PhongChieu>(new Action<PhongChieu>(this.attach_PhongChieus), new Action<PhongChieu>(this.detach_PhongChieus));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", DbType="VarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenMH", DbType="NVarChar(100)")]
		public string TenMH
		{
			get
			{
				return this._TenMH;
			}
			set
			{
				if ((this._TenMH != value))
				{
					this.OnTenMHChanging(value);
					this.SendPropertyChanging();
					this._TenMH = value;
					this.SendPropertyChanged("TenMH");
					this.OnTenMHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="LoaiManHinh_DinhDangPhim", Storage="_DinhDangPhims", ThisKey="id", OtherKey="idLoaiManHinh")]
		public EntitySet<DinhDangPhim> DinhDangPhims
		{
			get
			{
				return this._DinhDangPhims;
			}
			set
			{
				this._DinhDangPhims.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="LoaiManHinh_PhongChieu", Storage="_PhongChieus", ThisKey="id", OtherKey="idManHinh")]
		public EntitySet<PhongChieu> PhongChieus
		{
			get
			{
				return this._PhongChieus;
			}
			set
			{
				this._PhongChieus.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_DinhDangPhims(DinhDangPhim entity)
		{
			this.SendPropertyChanging();
			entity.LoaiManHinh = this;
		}
		
		private void detach_DinhDangPhims(DinhDangPhim entity)
		{
			this.SendPropertyChanging();
			entity.LoaiManHinh = null;
		}
		
		private void attach_PhongChieus(PhongChieu entity)
		{
			this.SendPropertyChanging();
			entity.LoaiManHinh = this;
		}
		
		private void detach_PhongChieus(PhongChieu entity)
		{
			this.SendPropertyChanging();
			entity.LoaiManHinh = null;
		}
	}
}
#pragma warning restore 1591
